apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Tahira-Nawaz/ArgoCD-App.git'
    targetRevision: HEAD
    path: k8s/staging
  destination:
    server: 'https://172.31.128.18:6443'
    namespace: app2-wordpress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
